### ISSUE TITLE
Rule for rest spread missuse

### ISSUE THREAD

**Issue by graingert** [bryanrsmith/eslint-plugin-prefer-object-spread#45]
I've seen code like:

```js
// bad
const foo = {
    ...{a, value: x + 3},
    ...stuff,
};

// good
const foo = {
    a,
    value: x + 3,
    ...stuff,
};
```

**Comment by bryanrsmith** [comment]
Good idea. I think it would be good to create a new rule for that rather than extend this one. I'd expect ESLint core to start accepting rules around object rest/spread soon, now that the proposal is pretty far along and is starting to be implemented by vendors, so I suggest opening an issue in the main ESLint repo.

**Comment by graingert** [comment]
@bryanrsmith 
@mysticatea said:

> It's not a part of ECMAScript yet.

it looks like it will have to be in a separate plugin first.
